### ISSUE TITLE
is this project abadoned

### ISSUE THREAD

**Issue by ufobat** [Altai-man/cro-ldap#12] opened 2021-02-08 12:35 UTC
Hey Altai-man, there haven't been much work on this repo. Is this project abadoned?

( I guess I need to go for perl5 mojo for my ldap application :-( )

**Comment by Altai-man** [comment] 2021-02-08 15:45
Hi.
It is not abandoned: to my understanding, it already allows the user to do various basic and not so basic things, tested against real servers. There were some issues with windows LDAP servers, but I was unable to reproduce it (hence fix).

I do not have time nor money right now to make it better and better every day so that people would see fresh commits and think it is not abandoned. :)

If you want, you can try it out for your task (the pitfalls possible will be the same as with every other Raku software right now, I believe). If something more exotic is missing - please report and I'll either try to fix it or will gladly consult about what / where to patch if you will be willing to do a patch or two.

**Comment by ufobat** [comment] 2021-02-08 20:24
thanks for the quick reply :-) what would you need to have in the lib in order add it the the regular eco system? (afaik it is not listed on modules.raku.org )

**Comment by Altai-man** [comment] 2021-02-08 23:05
>what would you need to have in the lib in order add it the the regular eco system?

Someone evaluating usage quality of this module. The main problem is (and was at the time of writing) I have no real usages for it, so I cannot really evaluate it from the user's perspective and if it has any worth in publishing, that's the main reason it is not listed in the eco.

**Comment by Altai-man** [comment] 2021-08-22 10:06
A-and no reaction since then, closing. Re-open if disagree.

**Closed as completed by Altai-man** 2021-08-22 10:06 UTC
